'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, RefreshCw, Clock, Zap, ChevronRight, Star, CheckCircle2 } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { useAutoGeneratedFacts } from '@/lib/auto-generation';
import type { Fact } from '@/types';

function FactCard({ fact, index }: { fact: Fact; index: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -20, scale: 0.95 }}
      transition={{ delay: index * 0.1 }}
      className="relative group"
    >
      <div className="absolute -inset-0.5 bg-gradient-to-r from-cyan-500 via-violet-500 to-cyan-500 rounded-2xl blur opacity-20 group-hover:opacity-40 transition-opacity" />
      <div className="relative bg-slate-900/90 backdrop-blur-xl border border-slate-800/50 rounded-2xl p-6 h-full">
        <div className="flex items-center justify-between mb-4 relative">
          <span className="px-3 py-1 text-xs font-medium bg-gradient-to-r from-cyan-500/20 to-violet-500/20 text-cyan-400 rounded-full border border-cyan-500/30 capitalize">
            {fact.category.replace('-', ' ')}
          </span>
          {fact.verified && (
            <span className="flex items-center gap-1 px-2 py-1 text-xs text-green-400">
              <CheckCircle2 className="w-3 h-3" /> Verified
            </span>
          )}
        </div>
        <h3 className="text-lg font-bold text-white mb-3 line-clamp-2 group-hover:text-cyan-400 transition-colors">{fact.title}</h3>
        <p className="text-sm text-slate-400 mb-4 line-clamp-3">{fact.shortExplanation}</p>
        <div className="flex items-center justify-between relative">
          <span className="text-xs text-slate-500">{fact.views.toLocaleString()} views</span>
          <Link href={`/facts/${fact.slug}`}>
            <Button size="sm" variant="ghost" className="text-cyan-400 hover:text-cyan-300">
              Read More <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          </Link>
        </div>
      </div>
    </motion.div>
  );
}

function CountdownTimer({ nextUpdateIn }: { nextUpdateIn: number }) {
  const [timeLeft, setTimeLeft] = useState(nextUpdateIn);
  useEffect(() => {
    const interval = setInterval(() => {
      setTimeLeft(prev => prev <= 1000 ? nextUpdateIn : prev - 1000);
    }, 1000);
    return () => clearInterval(interval);
  }, [nextUpdateIn]);
  return (
    <div className="flex items-center gap-3">
      <div className="relative w-12 h-12">
        <svg className="w-12 h-12 -rotate-90" viewBox="0 0 48 48">
          <circle cx="24" cy="24" r="20" stroke="currentColor" strokeWidth="3" fill="none" className="text-slate-700" />
          <circle cx="24" cy="24" r="20" stroke="currentColor" strokeWidth="3" fill="none" className="text-cyan-400" strokeDasharray={125.66} strokeDashoffset={125.66 * (1 - timeLeft / nextUpdateIn)} strokeLinecap="round" />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="text-xs font-bold text-cyan-400">{Math.ceil(timeLeft / 1000)}s</span>
        </div>
      </div>
      <div>
        <p className="text-sm text-white font-medium">Next Facts In</p>
        <p className="text-xs text-slate-400">3 new facts will appear</p>
      </div>
    </div>
  );
}

export function AutoFactsFeed({ intervalMs = 60000, factsPerInterval = 3, className = '' }: any) {
  const { facts, newFactsCount, lastUpdate, isGenerating, refreshNow, nextUpdateIn } = useAutoGeneratedFacts(intervalMs, factsPerInterval);
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return <div className={`glass rounded-3xl p-8 animate-pulse ${className}`}><div className="h-8 bg-slate-800 rounded w-1/3" /></div>;
  return (
    <div className={`space-y-8 ${className}`}>
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-violet-500 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white">Auto-Generated Facts</h2>
            <p className="text-sm text-slate-400">New facts every minute</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <CountdownTimer nextUpdateIn={nextUpdateIn} />
          <Button onClick={refreshNow} disabled={isGenerating} className="bg-gradient-to-r from-cyan-500 to-violet-500">
            <motion.div animate={{ rotate: isGenerating ? 360 : 0 }} transition={{ duration: 1, repeat: isGenerating ? Infinity : 0 }}>
              <RefreshCw className="w-4 h-4 mr-2" />
            </motion.div>
            {isGenerating ? 'Generating...' : 'Generate Now'}
          </Button>
        </div>
      </div>
      <div className="glass rounded-2xl p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-8">
            <div className="flex items-center gap-2"><Zap className="w-5 h-5 text-cyan-400" /><div><p className="text-2xl font-bold text-white">{facts.length}</p><p className="text-xs text-slate-400">Total Facts</p></div></div>
            <div className="flex items-center gap-2"><Sparkles className="w-5 h-5 text-violet-400" /><div><p className="text-2xl font-bold text-white">{newFactsCount}</p><p className="text-xs text-slate-400">New This Session</p></div></div>
            <div className="flex items-center gap-2"><Clock className="w-5 h-5 text-amber-400" /><div><p className="text-sm font-medium text-white">Last: {lastUpdate.toLocaleTimeString()}</p><p className="text-xs text-slate-400">Auto-refresh every 60s</p></div></div>
          </div>
          <div className="flex items-center gap-2">
            <motion.div className="w-3 h-3 rounded-full bg-green-500" animate={{ scale: [1, 1.2, 1], opacity: [1, 0.5, 1] }} transition={{ duration: 2, repeat: Infinity }} />
            <span className="text-sm text-green-400 font-medium">LIVE</span>
          </div>
        </div>
      </div>
      <AnimatePresence mode="popLayout">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {facts.slice(0, 9).map((fact: Fact, index: number) => <FactCard key={fact.id} fact={fact} index={index} />)}
        </div>
      </AnimatePresence>
    </div>
  );
}

export default AutoFactsFeed;
